language: node_js
node_js:
- '12'
- '8'
- '10'
after_success: npm run coveralls
deploy:
  provider: npm
  email: hg8496@cstolz.de
  api_key:
    secure: ApnqiRbvwoYxyjA/LgP0x/cgfGlFPNw1fr5odHYaOuDTbUzIxdGbjwb62+YrYm4dr6+JyM83uftvXqRv34nd4Ihtjscmd0+Iyn+sWikVNRBGmCyYDfGISQgrZLUYmH4p6e1pZAbpsgh2K6AtDiDGZWjS0PPFqhvUk+o8LOUUaibNGANhRXH4dP0zd0GgLHIGAT69eOzwbm40LjInFogf89aAzazRUfGPF9h3CI4zri2ls3vTDQ+f2yvYSuvENEPhwzEddNsHzpDDd4xI0BKLTjRoUa866n9zgnv2uT9AalPtrKipLaPru8ETOOd0H5mU1KoaOZBhDutzkrxMQ5FG9uLkh+jOOSQitbJDMLKbTioJCABJyQBovgpQQq2V/0nrpHu7a3fE2eNOQgSPfCfOGh32V3RJKVd9pHyfVKo4ey99xUaANQrm9WtmGoCoLBkIcuLvW1qbLYGbhcEdNF977/wEGS0duzuCpS9hfMmqmMKnBLokFy6F8b8cWy9nlG0C87C82TGb0JVX6kc40hoO4xmSR6FtOnqdEQQpaTAstie+xU00dd5LSN+GWIFvA8kNXLU49QAVemNjTXr9tOychTAUHlFB5oPS4YjBvDmadq773W9aWH468DtglbzmjdIIkSGgNDlmjAceuDS+zWtW24z1S5okAIEG40USZbhgXUQ=
  on:
    tags: true
    repo: hg8496/energyday-creator
    node: 12
  skip_cleanup: true
