language: node_js
node_js:
- '8'
- '10'
- '12'
after_success: npm run coveralls
deploy:
  provider: npm
  email: hg8496@cstolz.de
  api_key:
    secure: MgPigPo7lDmy4NnNOdyu9v8o7qWyWIB4OTCpjTqwiaTqP8PGd/BIFtS4e3KBURdGlyj5781z6lRf0yblxG8aWmCYIjhisvV/ZiM92VzeYXgNeTBwF5QVWWNb/tkF8CqNdyChp4w1V5nbJVH20ZoJC0ovASA1X7VvknRbEpwIYao2Vma4RXbtdn+gj0Q90YSnDLzzqh4ICwW4zG3e8wwnIgqWyD9f0GvcTBltBNJe/UE2+l5WyjFCaJf9njjSs7VpylgZORwudYbSAbMj3vlSJkx5MecTNnO3m6Zhl6fSGoYUbeiPh3FK+niBmt3nazCsYOTyAOSq8K+NrBj6V2W5Y6NygTUr9qsl5JCzfYlidyYxOjIIqSTpqwAhE76FoeHorHJHl1qH0CMmQlW6eXbbEm7SDDMtaXXQbck9ORhiQucQy4rtXENWOKyY+TC7BpJtmiCMnKTuVA5LM/HTd1EdUnJSzYApqiqjxvgWN9fa+C/r2//SDSiYfDJDO+IODF9EJqiRKG6kxmsr/4Qi+d2lfpFhdETvfFmZcf3CqUCcXYtkO6IpcturApwp9egIXpCzP68U8CEDgLs1Uo3DiSSNkRhmdZQrsvCVQvEnk/+jMmOUsLUp0zw7f680hjcv2ytVcrl/V7qnraFoX39ozd5KhQ+6r/k+3RjIvr5W2xOoG4o=
  on:
    tags: true
    repo: hg8496/energyday-creator
